### ISSUE TITLE
The report receives the interrupted status if there are a large number of allure annotations

### ISSUE THREAD

**Issue by AlexMatyushenko** [reportportal/allure-java#34]
**Describe the bug**
If there are a large number of annotations @owner,@epic, @feature, @story, the report receives the status interrupted and not a single test is displayed in it

**Steps to Reproduce**
Run a large number of tests with a large number of Allure annotations

**Expected behavior**
The report in the report portal is generated correctly

**Actual behavior**
The report has status:interrupted. It's empty

**Dependency versions**
agent-allure-testng:5.2.1

**Additional context**
[rp-io-45] ERROR com.epam.reportportal.utils.SubscriptionUtils - [102] ReportPortal Finish test item execution error
retrofit2.adapter.rxjava2.HttpException: HTTP 400 Bad Request
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[rp-io-46] ERROR com.epam.reportportal.utils.SubscriptionUtils - Start test item completed with error 
retrofit2.adapter.rxjava2.HttpException: HTTP 400 Bad Request
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
![image](https://github.com/user-attachments/assets/3772433c-7d83-47b8-b23a-9cf0b2a4fa10)

**Comment by AlexMatyushenko** [comment]
@HardNorth can you help me?

**Comment by AlexMatyushenko** [comment]
@HardNorth Why are these annotations added to the ReportPortal report as key:value? They look like this and are of no use, clicking on them does not filter
![image](https://github.com/user-attachments/assets/d8d62f2e-04ce-4635-8401-d2b44f00f81f)

**Comment by HardNorth** [comment]
@AlexMatyushenko Because somewhere in your code something like this is called:
```java
Allure.feature("my-feature");
```

**Comment by AlexMatyushenko** [comment]
@HardNorth That's right, and there are many such annotations. The project is big.
Is it possible to make a setting so that these annotations do not appear in the ReportPortal report?

**Comment by HardNorth** [comment]
@AlexMatyushenko No, there is no such option.

**Comment by AlexMatyushenko** [comment]
@HardNorth tell me how I can see the service-api logs? 
The only log that I can read now is in the description. 400 Bad Request

**Comment by HardNorth** [comment]
@AlexMatyushenko This question is related to backend part, it's not my area.

**Comment by HardNorth** [comment]
@AlexMatyushenko 
Done. Use: https://github.com/reportportal/allure-java/releases/tag/agent-allure-testng-5.4.2
It just sort attributes by key and cut them to maximum allowed number.
